[package]
name = "argument"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A small command line interface library with help pages, built on argument-parser"
repository = "https://github.com/mitsuhiko/argument"
keywords = ["cli", "argument", "parser", "help", "command-line"]
categories = ["command-line-interface"]
readme = "README.md"
license = "Apache-2.0"
documentation = "https://docs.rs/argument"

[dependencies]
argument-parser.workspace = true
