[package]
name = "argument-parser"
version = "0.0.1"
edition = "2021"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "a not yet published argument parsing library. Mail me if you have questions."
license = "Apache-2.0"

[dependencies]
