[package]
name = "argument-parser"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A low-level, dependency free command line parser following POSIX conventions"
repository = "https://github.com/mitsuhiko/argument"
keywords = ["cli", "argument", "parser", "getopt", "posix"]
categories = ["command-line-interface", "parser-implementations"]
readme = "README.md"
license = "Apache-2.0"
documentation = "https://docs.rs/argument-parser"
